### ISSUE TITLE
Stuck in loading screen when joining team using Chrome

### ISSUE THREAD

**Issue by tbreier** [mattermost/platform#3774]
#### Summary
Joining a team gets you stuck in a loading screen.

#### Steps to reproduce

Using version 3.3 RC1 - Chrome 52.0.2743.116 (64-bit):
1. Have a team that anyone on the server can join
2. Join the team on /select_team page

#### Expected behavior

The user gets added to the team and gets redirected to the team's town square.
When I use Safari 9.0.3 (10601.4.4), this works.

#### Observed behavior

User gets added to the team (can be seen in the database or by other users in the team), but the redirect to /teamname/channels/town-square gets stuck in a loading screen:

![image](https://cloud.githubusercontent.com/assets/2110273/17534949/b3b30e40-5e40-11e6-872d-3dc792dacee6.png)

Loading /teamname/channels/town-square manually in a different tab loads the town square as expected.

**Comment by enahum** [comment]
Hi @tbreier,

This should be fixed when RC3 is cut, can you re-test once RC3 is released?

**Comment by tbreier** [comment]
Thanks for your quick response @enahum! I will do that.

**Comment by jasonblais** [comment]
Thanks again for the report @tbreier! 

[We just cut RC3](https://github.com/mattermost/platform/issues/3702#issuecomment-238720045) where this issue should be fixed.

Please let us know if the issue still occurs?

**Comment by tbreier** [comment]
It's still happening for me @jasonblais @enahum.

I am running https://github.com/mattermost/platform/commit/805659239098a0b382a2a8bad704c2e91ab38ed6 through Docker on OS X, and it seems to be only happening in Chrome. Works fine in Safari, have not tested in other browsers.

**Comment by enahum** [comment]
weird, it does work for me in Chrome

**Comment by tbreier** [comment]
Hmm.... Do you know if there is any further data/information I could provide?

**Comment by jasonblais** [comment]
Thank you @tbreier, I was able to reproduce it on RC3 as well (on Chrome).

I've [reopened the Jira ticket](https://mattermost.atlassian.net/browse/PLT-3846), and we'll investigate it further. 

Appreciate your report! Very helpful

**Comment by jasonblais** [comment]
Quick update @tbreier, we're about to cut RC5, which should fix the problem. I'll give an update once it's been done.

Thanks again for the report!

**Comment by tbreier** [comment]
Tested on https://github.com/mattermost/platform/commit/c6d5448c7540e06a78063b6b363b41a261fd66c3. Everything works as expected! Thank you @jasonblais @DavidLu1997 😄
