### ISSUE TITLE
Enter key does not send messages

### ISSUE THREAD

**Issue by Maverick1872** [mattermost/platform#4393]
#### Summary
Enter does not send messages when window is snapped left or right in Windows. Instead of sending the message it adds a new line in the text box.

#### Steps to reproduce
Version 3.3.0
Open mattermost web app
Snap window to right or left of monitor
Type message
Hit Enter

#### Expected behavior
Expected enter to send message

#### Observed behavior
This seems to only be happening when the width causes the left nav to collapse to the menu button. (mobile displays?) Tried to find the pixel width that the issue starts occuring on, was a little unsuccessful but I know for a fact that it happens when view is 765px wide. (tested in firefox mobile dev console)

#### Possible fixes
Not sure quite where to be honest. Will have to do with how you are resizing the view on small devices.

**Comment by lfbrock** [comment]
Hi @Maverick1872, 

I think this is fixed on master.

Can you sign up to https://pre-release.mattermost.com and use the Public Test Channel to confirm it's not an issue anymore?

**Comment by Maverick1872** [comment]
Enter key is working to send messages on pre-release, but looks like they are not actually sending. Get a "Retry - Cancel" button to the right of each message. They will send after the nav collapses initially but much more narrow than that width it will not send. 

Using my 1980x1200 monitor in portrait, snapped to either side the issue persists with them not sending.

Summary - Enter key now sends messages no matter what. If the window is much more narrow than when the nav bar collapses, messages fail to send consistently.

**Comment by lfbrock** [comment]
Okay thanks @Maverick1872 - we're trying to reproduce the new issue you're having with the retry-cancel but having trouble, usually that happens when there's a connection issue. How often were you seeing it happen on the smaller size?

**Comment by jasonblais** [comment]
Hey @Maverick1872, were you seeing the retry-cancel error showing consistently or only sometimes when trying to send a message?

**Comment by jasonblais** [comment]
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information.
