### ISSUE TITLE
"New messages below" indicator

### ISSUE THREAD

**Issue by S6066** [mattermost/platform#5013]
http://i.imgur.com/S3pG7E2.jpg  
MM 3.6.0-rc2 Team Edition  
As you can see, I'm at the bottom, but I still have the "New messages below" thing.

**Comment by jasonblais** [comment]
Thanks @S6066! 

1) Does this reproduce for you each time?
2) Does this reproduce for you only on the Android app, or also on browser/desktop app?
3) What happens when you click on the "New message below" bubble? 
4) What happens if you try to scroll to the bottom of the channel? Does the bubble disappear then?

**Comment by S6066** [comment]
1. When I'm on another channel then go to some channel with new messages, yes  
2. Also on desktop app but only in mobile view.  
3. Nothing happens  
3. Nothing since I'm already at the bottom. But when I scroll up then down it disappears

**Comment by jasonblais** [comment]
Thanks @S6066 for following up.

Have been trying to reproduce but unable to so far so asking a couple of more questions:

1. I'm wondering if this is reproducing on the final build [available for download here](https://about.mattermost.com/download)
2. Which desktop app version and operating system does it reproduce?
3. Which Android device do you have?

**Comment by S6066** [comment]
2. When clicking on "Help" on PC I have a menu with "mattermost docs" and "version 1.3.0". I'm on windows 10 x64.  
3. Meizu M2 on Android 5.1 (with Flyme 5.1.11.0G)  

1/ I tried on my PC with mobile view, I never have the "new messages below" bubble.

(Why is there link preview for buttons like flag, channels, reply, etc ? it's horrible http://i.imgur.com/NkA4OoE.png)

**Comment by jasonblais** [comment]
Thanks for the additional information ,very helpful.

For 1, do you mean you no longer see the "new messages below" bubble? 

Can you help post a screenshot of the About Mattermost dialog from **three-dotted Main Menu > About Mattermost**?

**Comment by S6066** [comment]
>For 1, do you mean you no longer see the "new messages below" bubble?

Yep  
>Can you help post a screenshot of the About Mattermost dialog from three-dotted Main Menu > About Mattermost?

http://i.imgur.com/LgkeaIi.png (on PC)

**Comment by jasonblais** [comment]
Thanks @S6066, I'm not really sure what might cause the new messages bubble to appear initially on RC2 but then not show at all..

Can you help upgrade to [the 3.6 release build](https://about.mattermost.com/download) and see if the issue gets resolved?

**Comment by jasonblais** [comment]
> Edit: Nevermind, I still have it on phone.

Ah, saw your edit now, I think I missed it earlier, sorry about that. I've asked a couple of our team members to see if they can reproduce the issue on their Android device with Mattermost 3.6.1

Is anyone else seeing an issue where the "New Messages Below" indicator in the center channel does not properly clear, until you scroll up and back down the channel?

**Comment by S6066** [comment]
>Can you help upgrade to the 3.6 release build and see if the issue gets resolved?

On client, right ? But on Android or PC ? On Android I already have the lastest version, on PC I only see the 3.5.0 version, which I installed.

**Comment by jasonblais** [comment]
I mean updating to the latest version for the Mattermost Server --> there were a few bug fixes between 3.6.0-rc2 and 3.6.1, and the issue might have been resolved since.

Our team member will test it out on Monday as well to try and replicate the issue

**Comment by S6066** [comment]
Didn't try on PC with phone view, but on Android, I never see it now

**Comment by jasonblais** [comment]
Hey @S6066, 

It should only appear if you switch to a channel and not all the messages are visible on your screen (i.e. there are more unread messages below).

I'm wondering if you could try testing the following and let me know the observed behaviour?

TEST 1:
1. User A: Go to a channel that is not Town Square
2. User B: Post a message "hey"
3. User A: Go back to Town Square

TEST 2:
1. User A: Go to a channel that is not Town Square
2. User B: Post enough new messages so that they don't all fit on your screen
3. User A: Go back to Town Square
4. User A: Scroll to the bottom of the channel

----

PS: A team member tried reproducing on their Android device but wasn't able to, so just trying to see in which instances this issue occurs.

**Comment by S6066** [comment]
TEST 1: Still have the bubble, I am at the bottom and have to scroll up and down to make it disappear.  
TEST 2: After scrolling to the bottom I don't see the bubble.

**Comment by jasonblais** [comment]
Thanks @S6066! I was able to reproduce it consistently with a file attachment, so I created a bug ticket here: https://mattermost.atlassian.net/browse/PLT-5348

@pepf would this be something you'd like to take a look, since you worked on the feature?

```
Repro:
1) User 1: go to channel X and change your desktop window size small, so that it's on mobile view
2) User 2: post a file attachment in channel Y
3) User 1: switch to channel Y

Observed: "New messages below" bubble doesn't disappear even though there's only one message in the channel. Clicking on the indicator does nothing

Expected: "New messages below" bubble disappears since you're at the bottom of the channel

NOTE: This also reproduces when there's only 1 or 2 new messages in the channel, but I couldn't reproduce it consistently with that use case.
```

**Comment by jasonblais** [comment]
Closing the issue here -- we'll track the issue here: https://mattermost.atlassian.net/browse/PLT-5348

It's open for community contributions if anyone is interested
